# Site settings
title: Vir치g Zolt치n personal site
description: The introductory page of a developer.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vir치g Zolt치n
user_description: I have been involved in creating robust (corporate governance and financial) systems as a backend and frontend developer. I collected experience in the development and operation of highly frequented pages. In addition, I have continually improved my knowledge of both client-side and server-based solutions along the lines of clean code. My hobbies are smart home, gardening, forestry, hiking and cycling.
user_title: Software Developer
email: mail@viragzoli.net
twitter_username: settenke
github_username: settenke
gplus_username: settenke
facebook_username: viragzoli
linkedin_username: viragzoli

# About experience
frameworks_text: I have worked with the main frontend and backend frameworks.
code_text: Mostly I'm programming PHP and JavaScript, but it's also in Arduino or Python.
tools_text: During my work, I use cloud-based solutions as well as various CI tools.

# Google-analytics
google-analytics:
  id: "UA-115056921-1"

exclude: ['package.json', 'src' , 'node_modules']
